'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '@/app/components/Footer.jsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({ children }) {
  return (
    <html lang="es" data-theme="simpsons">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-yellow-50 to-orange-50`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
